### ISSUE TITLE
Strange problem with eleminterpolate

### ISSUE THREAD

**Issue by stoiver** [lyc102/ifem#1]
@lyc102 just using ifem to produce an adaptive shallow water equation solver. But ran into a strange problem with eleminterpolate when interpolating from a fine mesh to a coarse mesh. 

For some reason the last command in eleminterpolate.m 

```
newp(tree(:,3)) = [];
```
doesn't seem to be applied (at least in some cases). 

I have attached an example where the error turns up (at least when using matlab R2017a)

[eleminterpolate_bug.txt](https://github.com/lyc102/ifem/files/3304402/eleminterpolate_bug.txt)
 
I can get around the problem by explicitly adding the command `newp(tree(:,3)) = [];` after the call to `eleminterpolate`. 

By the way, ifem is an impressive package, well done.

**Comment by lyc102** [comment]
Thanks. I will take a look and let you know the problem. — Long

**Comment by stoiver** [comment]
@lyc102  it seems that for my example `NTin > NTf` and so the execution never gets to the command `newp(tree(:,3)) = [];`. A simple fix is to change the `elseif` to `else` for the fine to coarse case.

**Comment by lyc102** [comment]
Yes. You are right. I looked at your example and found when the tree is obtained by the coarsening, NTf could be smaller than NTin not exactly equal. I have pushed the update to github. Thanks again. — Long
