### ISSUE TITLE
typos in HodgeLaptest.m and HodgeLapfemrate.m

### ISSUE THREAD

**Issue by Terenceyuyue** [lyc102/ifem#5]
HodgeLaplacianE(node,elem,pde,bdFlag,option)  <--->    HodgeLaplacianE(node,elem,bdFlag, pde, option)

mfemHodgeLap(node,elem,bdFlag,pde,option)  <-----> mfemHodgeLap(mesh,pde,option,varargin)

**Comment by lyc102** [comment]
Thanks. Have corrected it. Will clean up and add more later. — Long
